# Generated by Django 5.1.6 on 2025-02-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0003_profile_name_alter_profile_age_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Using Star-Burst-Stream', max_length=100),
        ),
    ]
